name: bibtool

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  bibtool:
    runs-on: macos-latest
    steps:
    - name: Checking out repository
      uses: actions/checkout@v3
    - name: Install bibtool
      run: brew install bib-tool
    - name: Run bibtool
      id: run-bibtool
      run: |
        shopt -s nullglob  # allow empty loops below
        cd paper
        for f in *.bib; do
          bibtool -R -r braces.rsc -r field.rsc -r improve.rsc -r sort_fld.rsc -r ./local.rsc -i $f -o _out_$f
          mv _out_$f $f
        done
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: bibtool-patch
