name: Build LaTeX diff document
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_latex_diff:
    runs-on: ubuntu-latest
    env:
      PAPER: ${{ github.event.repository.name }}
      MAIN: ${{ github.event.pull_request.base.sha }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download LaTeX styles
        run: |
          curl -OL https://github.com/dpo/latex-styles/archive/refs/heads/master.zip
          unzip master.zip
      - name: Compile LaTeX diff
        id: compileLaTeXdiff
        uses: xu-cheng/latex-action@v3
        with:
          texlive_version: 2023
          root_file: |
            ${{ env.PAPER }}-diff${{ env.MAIN }}.tex
          working_directory: paper
          extra_system_packages: "git patch"
          latexmk_shell_escape: true
          pre_compile: git config --global --add safe.directory /github/workspace && latexdiff-vc --git --flatten --disable-auto-mbox --exclude-safecmd="Cref,Cref\*,hspace" --allow-spaces --no-links -r ${{ env.MAIN }} ${{ env.PAPER }}.tex
        env:
          TEXINPUTS: ".:$PWD/../latex-styles-master/styles//:"
          BSTINPUTS: ".:$PWD/../latex-styles-master/styles/common"
          BIBINPUTS: ".:$PWD/../latex-styles-master/share"
        continue-on-error: true
      - name: Upload PDF
        if: steps.compileLaTeXdiff.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: Success--Here-is-the-Diff-PDF
          path: |
            paper/${{ env.PAPER }}-diff${{ env.MAIN }}.pdf
      - name: Upload build logs
        if: steps.compileLaTeXdiff.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: Diff-Build-Failed--Here-are-the-Logs
          path: |
            paper/**/*.log
      - name: Fail job if build failed
        if: steps.compileLaTeXdiff.outcome == 'failure'
        run: exit 1
