name: Build response-to-referees
on:
  push:
    branches:
      - master
      - main
    paths: ['paper/response-to-referees.tex']
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['paper/response-to-referees.tex']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compile LaTeX document
        id: compileLaTeXdocument
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            response-to-referees.tex
          working_directory: paper
          extra_system_packages: "git patch"
          latexmk_shell_escape: true
          pre_compile: git config --global --add safe.directory /github/workspace
      - name: Upload PDF
        if: steps.compileLaTeXdocument.outcome == 'success' && github.event_name != 'push'
        uses: actions/upload-artifact@v4
        with:
          name: Success--Here-is-the-response-to-referees-PDF
          path: |
            paper/response-to-referees.pdf
      - name: Upload build logs
        if: steps.compileLaTeXdocument.outcome == 'failure' && github.event_name != 'push'
        uses: actions/upload-artifact@v4
        with:
          name: Build-Response-Failed--Here-are-the-Logs
          path: |
            **/*.log
      - name: Fail job if build failed
        if: steps.compileLaTeXdocument.outcome == 'failure'
        run: exit 1
