name: indent

on:
  push:
    branches:
      - 'main'
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checking out repository
      uses: actions/checkout@v4
    - name: Install latexindent and bibtool
      run: brew install latexindent bib-tool
    - name: Run latexindent
      id: run-latexindent
      run: |
        shopt -s nullglob  # allow empty loops below
        for f in *.tex; do latexindent -l ./localSettings.yaml -m -r -w $f; done
        rm -f *.bak[0-9] indent.log
    - name: Run bibtool
      id: run-bibtool
      run: |
        shopt -s nullglob  # allow empty loops below
        cd paper
        for f in *.bib; do
          bibtool -R -r braces.rsc -r field.rsc -r improve.rsc -r sort_fld.rsc -r ./local.rsc -i $f -o _out_$f
          mv _out_$f $f
        done
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
