name: latexindent

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checking out repository
      uses: actions/checkout@v3
    - name: Install latexindent
      run: brew install latexindent
    - name: Run latexindent
      id: run-latexindent
      run: |
        shopt -s nullglob  # allow empty loops below
        cd paper
        for f in *.tex; do latexindent -l ./localSettings.yaml -m -r -w $f; done
        # for f in *.bib; do latexindent -l ./localSettings.yaml -m -r -w $f; done
        rm *.bak[0-9]
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
