name: add artifact links to pr
on:
  workflow_run:
    workflows: ["Build LaTeX document", "Build LaTeX diff document"]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    runs-on: [ubuntu-latest]
    steps:
      - name: add artifact links to pull request and related issues step
        uses: veitbjarsch/artifacts-url-comments@main
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: "Status:"
            format: "name"
            addTo: "pull"
